version: "3.8"
services:
  db:
    build: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD:
    volumes:
      - mysql-data:/var/lib/mysql


  php-apache:
    build: .
    restart: always
    ports:
      - "80:80"
    environment:
      HOST: db
    depends_on:
      - db
    volumes:
      - uploaded-files:/var/www/html/src/uploads
      - ./src:/var/www/html/src
      - ./index.php:/var/www/html/index.php


  phpmyadmin:
    image: phpmyadmin:apache
    ports:
      - "8080:80"
    restart: always

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - '3000:80'
      - '443:443'
    volumes:
      - mercure_data:/data
      - mercure_config:/config


volumes:
  mysql-data:
  uploaded-files:
  mercure_data:
  mercure_config:

