version: "3.8"
services:
  db:
    build: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD:
    volumes:
      - mysql-data:/var/lib/mysql


  php-apache:
    build: .
    restart: always
    ports:
      - "80:80"
    environment:
      HOST: db
    depends_on:
      - db
    volumes:
      - uploaded-files:/var/www/html/src/uploads
      - ./src:/var/www/html/src
      - ./index.php:/var/www/html/index.php

    env_file:
      - mercure-variables.env


  phpmyadmin:
    image: phpmyadmin:apache
    ports:
      - "8080:80"
    restart: always

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins http://localhost


    env_file:
      - mercure-variables.env


    ports:
      - '3000:80'
    volumes:
      - mercure_data:/data
      - mercure_config:/config


volumes:
  mysql-data:
  uploaded-files:
  mercure_data:
  mercure_config:

